### ISSUE TITLE
PMIx_Init(NULL) supported?

### ISSUE THREAD

**Issue by PHHargrove** [pmix/master#12]
The man page for pmix_init.3 is clear that a `NULL` argument is legal:
```
Passing a parameter of NULL for this parameter is allowed if
the user wishes solely to initialize the PMIx system and does not
require return of the identifier at that time.
```

However, PMIx_Init() in src/client/pmix_client.c has the following lines as its first executable statements:
```
    if (NULL == proc) {
        return PMIX_ERR_BAD_PARAM;
    }
```

A simple test with the pmix-1.1.1 tarball confirms a return of -19 for `PMIx_Init(NULL)`

**Comment by rhc54** [comment]
Hmmm....obviously, something got out-of-phase. Thx!
