### ISSUE TITLE
User object for notifications

### ISSUE THREAD

**Issue by rhc54** [pmix/master#120]
A user would like to include a void* object when registering for notifications that will be returned to them whenever that specific notification callback function is executed. I believe this can be accomplished without modifying the current notification registration API by simply adding a new key (PMIX_EVENT_RETURN_OBJECT) that contains a pointer object as its value.

Only change required is to the event notification code so that it (a) retains an object provided via that key, and then (b) returns it in the cbfunc array of info.

**Comment by dsolt** [comment]
So the error handlers are called with a chain of events in the form of PMIx_Info's and this PMIx_Info is added to the end with the specific value provided during registration for that handler?   It  looks good to me.

**Comment by rhc54** [comment]
Yep, that's the way it works. I didn't want to modify the handler's signature, and this seemed simple enough.

Thanks!
