### ISSUE TITLE
flock is not available on Solaris

### ISSUE THREAD

**Issue by ggouaillardet** [pmix/master#136]
```src/dstore/pmix_esh.c``` uses the ```flock``` function in order to lock (shared or exclusive) or unlock a file.

unfortunatly, this is not available on Solaris (and maybe some other OSes as well).
sadly, i have no alternative to suggest yet.

could someone please find a way to fix this ?

**Comment by rhc54** [comment]
This won't affect the OMPI v2.0.1 release, but will block us from the 2.1 release. OMPI has methods for dealing with this problem - perhaps we can borrow from the opal/shmem support over there?

**Comment by artpol84** [comment]
@rhc54 I tried to assign @karasevb but failed. Do we need to do something special to enable this?

**Comment by rhc54** [comment]
He has to join the organization - I just sent him an invite.

**Comment by artpol84** [comment]
@rhc54 thank you!

**Comment by artpol84** [comment]
@ggouaillardet do you know if fcntl locking is supported on Solaris?
If it is we will provide configuration-driven way to choose between flock and fcntl.

**Comment by artpol84** [comment]
I'm talking about Advisory Record Locking:
http://man7.org/linux/man-pages/man2/fcntl.2.html

We may even improve concurrency of DSTOR by locking only portions of the shmem files (if this is possible)

**Comment by ggouaillardet** [comment]
that is supported, at least per the man page.
and since ROMIO uses that, i do believe this is supported anywhere (except maybe under windows, but we do not have to care any more)

**Comment by artpol84** [comment]
Great, thank you!

**Comment by PHHargrove** [comment]
For more info on replacing flock() w/ fcntl() you may wish to have a look at [this page](https://www.perkin.org.uk/posts/solaris-portability-flock.html)

**Comment by artpol84** [comment]
Closing through https://github.com/pmix/master/pull/157
