### ISSUE TITLE
PR backward compat changes to v1.2

### ISSUE THREAD

**Issue by artpol84** [pmix/master#197]
@jjhursey @rhc54 Setting this for tracking purposes.
@karasevb Please PR #189 to v1.2

**Comment by artpol84** [comment]
@karasevb we also need to add pmi1/pmi2 tests to Mellanox Jenkins.

To launch them I use `pmix_test` with `-e` parameter, i.e.
```
$ pmix_test -e pmi_test
$ pmix_test -e pmi2_test
```

Note that we need to add `-o` option to them to make testing uniform.

**Comment by jjhursey** [comment]
Closed in PR #199
