### ISSUE TITLE
Export only API symbols

### ISSUE THREAD

**Issue by igor-ivanov** [pmix/master#26]
I would like to suggest controlling the exported symbols of pmix shared library.
* It prevents abuse of undocumented APIs of your library. Symbols that are not exported from the library cannot be used.
* It reduces the risk of symbol collision between your library and other libraries.
* It reduces the startup time of programs linked to the library.

Possible ways:
* using -fvisibility=hidden and “visibility” attribute
* using map file

Probably the first is more interesting to support different platforms, compilers etc.

**Comment by rhc54** [comment]
@igor-ivanov Please see if you can do so - would resolve a few problems and I do agree with the reasons.

**Comment by igor-ivanov** [comment]
@rhc54 I will do
