### ISSUE TITLE
dstore/pthread locking brakes some SLURM configurations

### ISSUE THREAD

**Issue by artpol84** [pmix/master#295]
#273 and #274 broke slurm. This is a blocker. I'll PR shortly and update.

**Comment by artpol84** [comment]
@karasevb

**Comment by artpol84** [comment]
https://github.com/pmix/master/pull/298#issuecomment-278706258

**Comment by jjhursey** [comment]
PRs #289 and #300 should have addressed this issue and have been merged in.
