### ISSUE TITLE
pmi2_client test:10 report failure under slurm/pmix

### ISSUE THREAD

**Issue by igor-ivanov** [pmix/master#34]
It seems that slurm/pmix report timeout error during the test. Setting SLURM_PMIX_TIMEOUT=3000 does not help. Additional investigation is needed.

Observation:
```
INFO  1 : PMI2_KVS_Get from 0 [RANK1-key-48=wwwwwwwwwwwwwwwwww] 0
INFO  1 : PMI2_KVS_Get from 0 [RANK1-key-49=xxxxxxxxxxxxxxxxxx] 0
FATAL 0 : PMI2_KVS_Get [RANK1-key-50=?] -1
srun: Job step aborted: Waiting up to 32 seconds for job step to finish.
srun: error: mir10: task 1: Exited with exit code 255
slurmstepd-mir9: mir9 [0] /pmixp_client.c:241 [errhandler] mpi/pmix: ERROR: Error handler invoked: status = -25, nranges = 0: Success (0)
srun: error: mir9: task 0: Exited with exit code 255
```

How to launch:
```
env PMIX_DEBUG=0 VERBOSE=3 srun -N2 --mpi=pmix ./pmi2_client 9
```

**Comment by igor-ivanov** [comment]
This test is named as 10 in PR https://github.com/pmix/master/pull/43

**Comment by igor-ivanov** [comment]
Checked 4a08830 Merge pull request #52 from igor-ivanov/pr/issue-26

The issue exists

**Comment by rhc54** [comment]
FWIW: the current head of the pmix master repo works with mpirun, so this appears to be something related to the slurm plugin:

```shell
$ mpirun -host bend001:2 -n 2 ./pmi2_client 9
INFO  spawned=0 size=2 rank=0 appnum=0
INFO  jobid=3214802945
INFO  TI1  : PASS
INFO  Rank 0 executing Put of key KEY-0
INFO  Rank 0 executing Fence
INFO  spawned=0 size=2 rank=1 appnum=0
INFO  jobid=3214802945
INFO  TI1  : PASS
INFO  Rank 1 executing Put of key KEY-1
INFO  Rank 1 executing Fence
INFO  Rank 0 executing Get of key KEY-0
INFO  Rank 1 executing Get of key KEY-0
INFO  tkey=KEY-0 tval=VALUE-0 val=VALUE-0 len=7
INFO  Rank 0 executing Get of key KEY-1
INFO  tkey=KEY-0 tval=VALUE-0 val=VALUE-0 len=7
INFO  Rank 1 executing Get of key KEY-1
INFO  tkey=KEY-1 tval=VALUE-1 val=VALUE-1 len=7
INFO  TI9  : PASS
INFO  tkey=KEY-1 tval=VALUE-1 val=VALUE-1 len=7
INFO  TI9  : PASS

```

**Comment by igor-ivanov** [comment]
yes, I believe that slurm/pmix plugin stuff

**Comment by igor-ivanov** [comment]
I am sharing my investigation result:

pmix/master@44a9990 PASS
pmix/master@ad45529 FAIL

Following code in pmix_hash_store() change test behaivoyr from FAIL to PASS
See: https://github.com/pmix/master/blob/e8ab8403b71ed4c7069e6fdeb874a080ac6d7353/src/util/hash.c#L87-L94

This change was introduced as part of following commit:
https://github.com/pmix/master/commit/44a9990719b7f0a85a5945d4d20072250fb07a84#diff-ca91c49cb2a11ac25844b103e3a07f43R85

My guess: may be slurm/pmix falls to loop not finding the key and exit by timeout.

Formally I can conclude that there is a fix as https://github.com/pmix/master/commit/44a9990719b7f0a85a5945d4d20072250fb07a84

**Open questions:**
- how does this change impact reported issue
- why behaivour on ompi/pmix and slurm/pmix is different before this change
- does slurm/pmix have issue with processing this case or not

@rhc54 @artpol84 do you have any idea

**Comment by artpol84** [comment]
@igor-ivanov  What exactly is failing in test10?
My understanding was that test itself was detecting the problem and error-exiting.

**Comment by igor-ivanov** [comment]
@artpol84 you have right understanding. Timeout issue reported by slurm is a result and not a root.
I can not understand difference in ompi/pmix and slurm/pmix test results. @rhc54 did not see issue with ompi/pmix.

**Comment by artpol84** [comment]
The changes that @igor-ivanov has identified to be important matters because in the `pmix_server_commit()` implementation we rely on this functionality:
https://github.com/pmix/master/blob/master/src/server/pmix_server_ops.c#L172:L186

Without it old data will remain in the hashtable regardless to the used RM. I'll try OMPI now.

**Comment by artpol84** [comment]
@rhc54 I can reproduce the problem with OMPI as well. I took the latest ompi master and compiled it against external pmix/master@ad45529.
Conclusion: **This was a bug in PMIx. It was affecting all RM implementations. The problem is fixed in the latest PMIx master.**

**Comment by igor-ivanov** [comment]
thank you @artpol84 one more unclear issue has been resolved.
Probably it is a time to close the issue.
