### ISSUE TITLE
PMIx needs to be given connection info for all procs in namespace at startup

### ISSUE THREAD

**Issue by rhc54** [pmix/master#36]
For instant on, we need to obtain the connection info for all procs in the namespace prior to their being started. This is the responsibility of the resource manager, but we need to define the key-value structure for passing it to us so the applications (and/or the MPI libraries underneath them) know how to retrieve it.

**Comment by igor-ivanov** [comment]
@rhc54 could you provide an example basing on your knowledge.

Just as an example. Is it something what is needed
```
enum {
	CONNECT_TYPE_IP = 0,
	CONNECT_TYPE_IB
};

#pragma pack(push, 1)
typedef struct {
	uint8_t type;
	union {
		struct {
			uint32_t addr;
			uint16_t port;
		} ip;
		struct {
			uint8_t gid[16];
			uint64_t service_id;
		} ib;
	};
} connect_t;
#pragma pack( pop )

```

**Comment by rhc54** [comment]
@igor-ivanov Something like that, yes. I believe there are two requirements here:

- the RM needs some way of getting connection info from the relevant fabric manager. In other words, given a process placement map of what proc is going on which node, the RM needs to get back the connection info for each process.
- the RM can then include the returned info in the register_nspace command so it can be provided to all launched processes

The alternative, of course, is for the fabric to change its library so it can compute the endpoint given some other, more abstract information (e.g., host and node rank of each process), or that the RM have an OS-based method for obtaining the info. For example, in the case of socket-based TCP, we use statically-assigned ports provided by the RM. Thus, the RM itself can handle the computation given a block of available port numbers (requires that one define a block of reserved ports for the kernel).

I'm not sure which way you folks want to go, and it may be that you'll need more than one solution to deal with backward compatibility if you want to support older device libraries.

**Comment by igor-ivanov** [comment]
@rhc54 thank you. So this format should be flexible to be easy extended

**Comment by rhc54** [comment]
@igor-ivanov yes - I honestly don't know what might be required in the future, and it will be very fabric dependent. So we have to devise some method for "tagging" the data to ensure each fabric can "get" their portion of the data - especially since there could be multiple sources that need to pass info (e.g., TCP and Infiniband).

**Comment by igor-ivanov** [comment]
@rhc54 My personal vision:
We do not know accurately how widely it will be used. Any flexible structure has a chance to be modified to meet new requirement (so there is a risk to get abi issue). So I would like to propose using raw buffer approach. Data should be put in well documented format. Getting new type we just define it`s layout and seeting a parser for it. In case someone sends new type of data to pmix library that does not support one it is easy processed.

Let say that it should be binary buffer (probably to be friendly we could share our pack/unpack buffering interface) and data should be filled in specified layout.
Example:
```
pack(1)
{
uint32_t size; /* total data size in byte */
uint32_t count; /* number of elements */
uint8_t type; /*  type of data */
    ...data...
uint8_t type; /*  type of data */
    ...data...
uint8_t type; /*  type of data */
    ...data...
...
}
```
Type of data is declared following a scheme https://github.com/pmix/master/issues/36#issuecomment-191117418 for example keeping in mind about network ordering.

**Comment by rhc54** [comment]
@igor-ivanov I think perhaps I haven't communicated clearly. The issue here isn't how the data should be sent down to the client. The question is: how does the PMIx server get it? Once we have the data, we can just include it as a "blob" in the nspace buffer we send down to each proc. But we need some mechanism for getting it.

As I said above, one way is for everyone to just compute endpoints from the location info we already provide. If that fits with Mellanox plans, then nothing more need be done. However, if the RM needs to do something specifically to obtain the endpoint info (e.g. pass the process map to the fabric manager and get the endpoint "blob" in return), then we need to define how that happens.

**Comment by igor-ivanov** [comment]
@rhc54 got it. Thanks.

**Comment by rhc54** [comment]
The list of required data to be provided has been posted here:
https://github.com/pmix/master/wiki/2.8-Pmix-Server-Data-Requirements
