### ISSUE TITLE
Failures on test suite

### ISSUE THREAD

**Issue by igor-ivanov** [pmix/master#38]
I am observing set of failures on our test suit.
Brief investigation shows following:

d3b1a11 Get the examples to run under mpirun from OpenMPI. Only exception is the dmodex example, although direct m
$./pmix_test -n 4 --ns-dist 3:1 --fence "[b | 0:]"
pmix_test.c:main: Test finished OK!

58de093 Add support for multiple calls to PMIx_Commit by simply concatenating all committed data. Any modification
$./pmix_test -n 4 --ns-dist 3:1 --fence "[b | 0:]"
ERROR [test_fence.c:309:test_fence]: smoky_nspace-0:1: PMIx_Get failed: -46 from smoky_nspace-0:2147483646, key key-f0:0
ERROR [test_fence.c:311:test_fence]: smoky_nspace-0:1: PMIx_Get failed (-1) from smoky_nspace-0:2147483646
ERROR [test_fence.c:309:test_fence]: smoky_nspace-0:0: PMIx_Get failed: -46 from smoky_nspace-0:2147483646, key key-f0:0
ERROR [pmix_client.c:132:main]: smoky_nspace-0:1 Fence test failed: -1
ERROR [test_fence.c:311:test_fence]: smoky_nspace-0:0: PMIx_Get failed (-1) from smoky_nspace-0:2147483646
ERROR [pmix_client.c:132:main]: smoky_nspace-0:0 Fence test failed: -1
ERROR [test_fence.c:309:test_fence]: smoky_nspace-0:2: PMIx_Get failed: -46 from smoky_nspace-0:2147483646, key key-f0:0
ERROR [test_fence.c:311:test_fence]: smoky_nspace-0:2: PMIx_Get failed (-1) from smoky_nspace-0:2147483646
ERROR [pmix_client.c:132:main]: smoky_nspace-0:2 Fence test failed: -1
ERROR [cli_stages.c:252:errhandler]: rank 0 with state 1 unexpectedly terminated.
ERROR [cli_stages.c:148:cli_cleanup]: rank 0 with state 1 unexpectedly terminated.
[warn] Epoll ADD(4) on fd 14 failed.  Old events were 0; read change was 0 (none); write change was 1 (add): Bad file descriptor
ERROR [cli_stages.c:252:errhandler]:  PMIX server Error handler with status = -25
ERROR [cli_stages.c:252:errhandler]:  PMIX server Error handler with status = -25
[warn] Epoll ADD(4) on fd 13 failed.  Old events were 0; read change was 0 (none); write change was 1 (add): Bad file descriptor
[warn] Epoll ADD(4) on fd 15 failed.  Old events were 0; read change was 0 (none); write change was 1 (add): Bad file descriptor
ERROR [pmix_test.c:167:main]: Test was aborted!

**Comment by igor-ivanov** [comment]
@rhc54 do you have any idea?

**Comment by rhc54** [comment]
@igor-ivanov Let me take a look later tonight - I'm sure it is something I did wrong, but I don't offhand know where it lies. My apologies for the error and the delay.

**Comment by igor-ivanov** [comment]
I have looked a bit but could not found out a root of issue. status says that key can not be found. May be data is corrupted during store step.

**Comment by igor-ivanov** [comment]
@rhc54 it is strange but jenkins running manually does not report issue for this test. I guess that may be difference in libevent linkage. Will look tomorrow.

**Comment by igor-ivanov** [comment]
@rhc54 observed issue really exists. jenkins`s behaivour can be explained by a bug in script that is fixed in https://github.com/pmix/master/pull/39
