### ISSUE TITLE
Opacity in PMIX_RANK_UNDEF processing

### ISSUE THREAD

**Issue by igor-ivanov** [pmix/master#40]
What scope of data we should return during get request by PMIX_RANK_UNDEF?
- both PMIX_LOCAL and PMIX_REMOTE
- PMIX_LOCAL
- PMIX_REMOTE

Current code returns PMIX_REMOTE scope. In other words get operation returns data stored during put with PMIX_REMOTE or PMIX_GLOBAL scopes.

**Comment by rhc54** [comment]
This is for the legacy APIs? If so, I would return both scopes as the legacy code doesn't support data locality.

**Comment by igor-ivanov** [comment]
We can control internal implementation of PMI/PMI2 API and always use PMIX_GLOBAL for example. It is not big issue.
We have potential issue in case PMIX_RANK_UNDEF is public. Sharing PMIX_RANK_UNDEF with users we must have predictable behaivour (at least common understanding and agreement).

**Comment by rhc54** [comment]
True. The common "native" usage is to retrieve data that is rank-independent - i.e., job-level data. This data isn't published by the ranks, but effectively has "global" scope since every proc is given an identical copy of it. So perhaps we just state that "undef" has "global" scope by default?

**Comment by igor-ivanov** [comment]
I think the same intuitively. Do you see any ways when a user can  get a key from unsuitable scope (saved as PMIX_LOCAL for example) using PMIX_RANK_UNDEF?

**Comment by rhc54** [comment]
Not really - I think we should be good. As you say, we don't do dmodex in this case, and so there shouldn't be any issue.
