### ISSUE TITLE
Warnings in tests

### ISSUE THREAD

**Issue by rhc54** [pmix/master#44]
pmi_client.c: In function ‘test_item5’:
pmi_client.c:308:104: warning: ISO C99 requires rest arguments to be used [enabled by default]
         log_error("PMIx and SLURM/PMI1 do not set 'PMI_process_mapping' (Do not mark test as failed)\n");
                                                                                                        ^
pmi2_client.c: In function ‘test_item3’:
pmi2_client.c:223:99: warning: ISO C99 requires rest arguments to be used [enabled by default]
         log_error("PMIx and SLURM/PMI2 does not set Job Attributes (Do not mark test as failed)\n");
                                                                                                   ^
pmi2_client.c: In function ‘test_item4’:
pmi2_client.c:258:100 warning: ISO C99 requires rest arguments to be used [enabled by default]
         log_error("PMIx and SLURM/PMI2 does not set Node Attributes (Do not mark test as failed)\n");
                                                                                                    ^
pmi2_client.c: In function ‘test_item6’:
pmi2_client.c:321:67: warning: ISO C99 requires rest arguments to be used [enabled by default]
         log_error("PMI2_KVS_Get should not find data w/o commit\n");
                                                                   ^

**Comment by igor-ivanov** [comment]
There is a fix for this in https://github.com/pmix/master/pull/43

**Comment by rhc54** [comment]
Thanks!

**Comment by igor-ivanov** [comment]
Fixed in https://github.com/pmix/master/pull/43
