### ISSUE TITLE
Provide single way for getting temporary folder

### ISSUE THREAD

**Issue by igor-ivanov** [pmix/master#46]
pmix_tmp_directory() should return identical way for server and client taking into account PMIX_SERVER_TMPDIR.

For RM's we also provide the convenient way to cleanup everything that was created by the PMIx libraries by keeping all libpmix files in the directory that is determined by RM. In this case all RM needs to do - is to remove this dir. To acheive that we pass the evn PMIX_SERVER_TMPDIR to the server library.
Now pmix server-side will create a socket file there. I think we need to create all dstore files there as well.
However pmix_tmp_directory() doesn't related to PMIX_SERVER_TMPDIR and provides information on where the application temp dir is located.
So we probably need to forward PMIX_SERVER_TMPDIR to the client side library and provide the way to access it from there.

**Comment by artpol84** [comment]
@igor-ivanov 
This is not what I meant when we discussed this.
`pmix_tmp_directory()` is targeted for the end-user application and it works properly now. 
However the client-side library should have a way to get the directory that was passed to the server side from RM through PMIX_SERVER_TMPDIR. We want to use it for the `dstore`

**Comment by artpol84** [comment]
@igor-ivanov 
This statement:
`pmix_tmp_directory() should return identical way for server and client taking into account PMIX_SERVER_TMPDIR.`
is somewhat confusing. `pmix_tmp_directory()` has nothing to do with `PMIX_SERVER_TMPDIR`.

**Comment by igor-ivanov** [comment]
@rhc54 could you think and share your opinion about.
Let me provide more details about initial point (may be this topic partially was discussed at https://github.com/pmix/master/issues/47).
We have two places when temp folder can be requested and used.
- end user can request to set or get current temporary folder using PMIX_TMPDIR key-info target. Probably pmix_tmp_directory() function was implemented to be used for this purpose;
- pmix library can use another or the same temporary folder for internal usage;

We would like to have single temporary folder for pmix library that could be used for storing internal data. @artpol84 and me talked about this topic and think that a location should be directed by RM. There are at least two suitable ways RM could use as passing key-info option to PMIx_server_init() and setting environment variable PMIX_SERVER_TMPDIR. 
What do you think if we could require from RM passing such inforamtion using one of these ways?
Should we separate these temporary folders according their needs?

**Comment by rhc54** [comment]
I don't believe we actually let the user _set_ the temporary directory as I'm not sure how that would work. The PMIX_TMPDIR value was provided so the client could discover the result of the cascade of options we check in pmix_tmp_directory.

If you look at the client init code, you'll see that the server passes a URI to the client via the PMIX_SERVER_URI envar. We then parse the value to extract the server's nspace/rank, and the path to the temporary directory where the rendezvous socket resides. So one option would be to just use that path (minus the actual filename of the socket at the end) as the server's tmpdir.

Alternatively, you could ask that the server-side library create and pass its tmpdir as another envar such as the one you propose. This has nothing to do with the RM, though - we can handle that in the PMIx server code.

IIRC, @artpol84 created the pmix_tmp_directory() function, and so I'll defer to him regarding its use. Note that as it stands today, all it does is check the usual envars to find the system temporary directory - it doesn't actually tell us where a client temp directory might exist. In ORTE, we create the client temp directory and pass that down as an info key ourselves, and pick it up in the client init. However, that's an option and not all RMs may do so.
