### ISSUE TITLE
how could pmix work together with openmpi

### ISSUE THREAD

**Issue by lilbedwin** [pmix/master#74]
I have install pmix-1.1.1 and compliled openmpi-1.8.5 with the following step:
1, ./configure --prefix=/usr/local/openmpi  --with-pmi=/usr/local/pmix --with-pmi-libdir=/usr/local/pmix/lib --with-slurm=no
2, make && make install

here is my questions:
Q1: Can I start a stand alone pmix server as the tracker of the openmpi workers, and make openmpi workers run correctly, I mean, they may use pmi_kvs_put, pmi_kvs_get and pmi_barrier to build the topology of the mpi world.
Q2: if answer to Q1 is yes, can I use tcp/ip but not unix domain socket in pmix server. It seems that there's no choice beside usock in pmix-1.1.1.

thanks a lot!

Liangbin Li

**Comment by rhc54** [comment]
I don't honestly see a way for this to work. The ORTE code in 1.8.5 has no idea how to setup the PMIx server and provide the required info for the application processes. I suppose you could try creating a standalone PMIx server as you describe, and then finding some way to pass the usock connection to the processes - but the server will reject the connection from those processes because it wasn't previously told about them.

OMPI 2.0 is getting ready to release, and it has PMIx support in it - would you be able to switch to it?

**Comment by lilbedwin** [comment]
Actually, I do not care about the opmi version. 
What I really need is creating a standalone pmi server to track the openmpi workers and help them to init the topology. But sadly, pmix seems not to work because of the usock limit, which makes it unable to schedule the workers and the tracker to different hosts.
I hope pmix can support this feature in the future release.

**Comment by rhc54** [comment]
You can certainly create a standalone server - we just don't provide it. The server convenience library we provide is only intended to give you the local support, and you'd have to add the cross-node communications. Without a resource manager behind it, you won't get the performance benefits such as "instant on", but it would still provide wireup support.

FWIW: we are working in a separate project on a scalable cross-node communication library. Once that is released, it wouldn't be too difficult to write a tool that combines the two libraries to provide a standalone service like you describe. It isn't yet clear if we will do so within PMIx itself - we are still debating about it, but might do so as an optional feature.

**Comment by asylvest** [comment]
@rhc54 are there any docs / examples out there of using PMIx with Open MPI 2.0?  I haven't been able to find anything.

**Comment by rhc54** [comment]
I'm not sure exactly what you are looking for - perhaps you could give me an example of what you are trying to do? PMIx is used internally to OMPI 2.x, so there isn't anything you need to "do" to use it in that respect. Did you want to directly call some of the APIs from your app?

**Comment by asylvest** [comment]
High level my use case is I'm trying to start up some kind of process manager / server on some machine, have a number of processes all running on separate machines connect to it, then create an intracommunicator and start making MPI calls like normal (I'm using OMPI 2.x).  Obviously normally you would do this with an `mpiexec` that lists all the hosts up front, but I'm trying to use Mesos where I need to launch a task on each machine separately and then have them connect up somehow.  Mesos provides a way to do this with an older version of MPICH that uses mpd, and there's some other code out there that does it with a newer version of MPICH that uses Hydra, but in both cases the underlying implementation of how that Mesos code does this is kind of brittle.

I have thoughts on how I can shoehorn Open MPI into doing what I need, but I was hoping PMIx would help with this.  If I'm totally misunderstanding what PMIx is intended for / how it might help in this case, just let me know. :o)

**Comment by rhc54** [comment]
Transferring this to https://github.com/open-mpi/ompi/issues/3211
