### ISSUE TITLE
pmix/autogen/config.h should not be installed

### ISSUE THREAD

**Issue by garlick** [pmix/master#98]
pmix.h includes pmix/autogen/config.h which leaks all kinds of non PMIX_ prefixed pre-processor symbols into any project that includes pmix.h.

PMIx may want _GNU_SOURCE defined but maybe my project doesn't?

PMIx may define HAVE_MUNGE_H because munge was included as a build dependency in its mock root, but that is no longer a true statement when my package is built in _its_ mock root with only _its_ dependencies present.  Etc, etc.

A possible workarround is [ax_prefix_config_h](http://www.gnu.org/software/autoconf-archive/ax_prefix_config_h.html)
> A package should not normally install its config.h as a system header, but if it must, this macro can be used to avoid namespace pollution by making a copy of config.h with a prefix added to all the macro names.

But the defintions in pmix.h look pretty clean to me.  Maybe it would not be that hard to tease apart any dependencies and keep config.h internal?

**Comment by rhc54** [comment]
I thought we removed that? No need for config.h to be in pmix.h

**Comment by rhc54** [comment]
I see what happened - a PR was created to do it, but it was never committed. Let me see if it can be updated and committed

**Comment by rhc54** [comment]
Hmmm...I'm going to have to wait for @jjhursey to become available as we just went thru a cycle of moving config.h stuff around so it would build in their system - let me loop him into this so we don't break something over there

**Comment by jjhursey** [comment]
Yeah this happened in PR #88 when we were trying to resolve a problem compiling a C++ application against an installed PMIx (See Issue #87).

We might not need all of `config.h`, but we need some of it for `pmix_config_bottom.h` to work properly for C++ programs. I modeled it's inclusion mechanism after how Open MPI does things. It might be worth revisiting if we need all of these pre-processor symbols or not.

**Comment by rhc54** [comment]
Just an FYI: I have fixed this in the MCA RFC, so it will hopefully be resolved soon.

**Comment by rhc54** [comment]
Has been fixed
